[package]
name = "handler"
version = "0.1.0"
authors = ["GreenCloud <hello@greencloudcomputing.io>"]
edition = "2021"

[dependencies]
hyper = { version = "0.14", features = ["full"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
tokio = "1.38.0"
